/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Ahisar Pranowo
 */
public class Dashboard_Mahasiswa extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard_Mahasiswa.class.getName());

    /**
     * Creates new form Dashboard_Mahasiswa
     */
    public Dashboard_Mahasiswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Button_Dashboard = new javax.swing.JButton();
        Button_ToDoList = new javax.swing.JButton();
        Button_Profile = new javax.swing.JButton();
        Button_Kst = new javax.swing.JButton();
        Button_Jadwal = new javax.swing.JButton();
        Button_Nilai = new javax.swing.JButton();
        Button_Tagihan = new javax.swing.JButton();
        Button_RMK = new javax.swing.JButton();
        Button_Logout1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Label_Mahasiswa = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Label_Prodi = new javax.swing.JLabel();
        Label_Sks = new javax.swing.JLabel();
        Label_Tagihan = new javax.swing.JLabel();
        Label_JadwalHariIni = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(30, 39, 46));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Button_Dashboard.setText("Dashboard");
        jPanel1.add(Button_Dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 176, 39));

        Button_ToDoList.setText("To-Do List");
        Button_ToDoList.setBorderPainted(false);
        Button_ToDoList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ToDoListActionPerformed(evt);
            }
        });
        jPanel1.add(Button_ToDoList, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 176, 39));

        Button_Profile.setText("Profil");
        Button_Profile.setBorderPainted(false);
        jPanel1.add(Button_Profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 176, 39));

        Button_Kst.setText("KST");
        Button_Kst.setBorderPainted(false);
        jPanel1.add(Button_Kst, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 176, 39));

        Button_Jadwal.setText("Jadwal");
        Button_Jadwal.setBorderPainted(false);
        Button_Jadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_JadwalActionPerformed(evt);
            }
        });
        jPanel1.add(Button_Jadwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 176, 39));

        Button_Nilai.setText("Transkrip Nilai");
        Button_Nilai.setBorderPainted(false);
        jPanel1.add(Button_Nilai, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 176, 39));

        Button_Tagihan.setText("Tagihan");
        Button_Tagihan.setBorderPainted(false);
        jPanel1.add(Button_Tagihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 176, 39));

        Button_RMK.setText("Registrasi Matakuliah");
        Button_RMK.setBorderPainted(false);
        jPanel1.add(Button_RMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 176, 39));

        Button_Logout1.setText("Logout");
        Button_Logout1.setBorderPainted(false);
        Button_Logout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Logout1ActionPerformed(evt);
            }
        });
        jPanel1.add(Button_Logout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 176, 39));

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        Label_Mahasiswa.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Label_Mahasiswa.setForeground(new java.awt.Color(255, 255, 255));
        Label_Mahasiswa.setText("Dashboard Mahasiswa");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_Mahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(785, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Label_Mahasiswa)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        jLabel1.setText("👋 Selamat Datang, ");

        Label_Prodi.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        Label_Prodi.setText("Program Studi :");

        Label_Sks.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        Label_Sks.setText("| [📚 SKS Diambil: ] ");

        Label_Tagihan.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        Label_Tagihan.setText("[💰 Tagihan: Rp: ] ");

        Label_JadwalHariIni.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        Label_JadwalHariIni.setText("📅 Jadwal Hari Ini:    ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Prodi)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_Sks, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Label_Tagihan, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_JadwalHariIni)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel1))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_Prodi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Sks)
                    .addComponent(Label_Tagihan))
                .addGap(29, 29, 29)
                .addComponent(Label_JadwalHariIni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_ToDoListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ToDoListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_ToDoListActionPerformed

    private void Button_JadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_JadwalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_JadwalActionPerformed

    private void Button_Logout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Logout1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_Logout1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard_Mahasiswa().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Dashboard;
    private javax.swing.JButton Button_Jadwal;
    private javax.swing.JButton Button_Kst;
    private javax.swing.JButton Button_Logout1;
    private javax.swing.JButton Button_Nilai;
    private javax.swing.JButton Button_Profile;
    private javax.swing.JButton Button_RMK;
    private javax.swing.JButton Button_Tagihan;
    private javax.swing.JButton Button_ToDoList;
    private javax.swing.JLabel Label_JadwalHariIni;
    private javax.swing.JLabel Label_Mahasiswa;
    private javax.swing.JLabel Label_Prodi;
    private javax.swing.JLabel Label_Sks;
    private javax.swing.JLabel Label_Tagihan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
