/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;


public class Dashboard_Dosen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard_Dosen.class.getName());

    /**
     * Creates new form Dashboard_Dosen
     */
    
    public Dashboard_Dosen() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Button_Presensi = new javax.swing.JButton();
        Button_KelasSaya = new javax.swing.JButton();
        Button_Nilai = new javax.swing.JButton();
        Button_Profile1 = new javax.swing.JButton();
        Button_Dashboard = new javax.swing.JButton();
        Button_Logout1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Label_Dosen = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(30, 39, 46));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Button_Presensi.setText("Presensi");
        Button_Presensi.setBorderPainted(false);
        Button_Presensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_PresensiActionPerformed(evt);
            }
        });
        jPanel1.add(Button_Presensi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 176, 39));

        Button_KelasSaya.setText("Kelas Saya");
        Button_KelasSaya.setBorderPainted(false);
        jPanel1.add(Button_KelasSaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 176, 39));

        Button_Nilai.setText("Nilai");
        Button_Nilai.setBorderPainted(false);
        jPanel1.add(Button_Nilai, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 176, 39));

        Button_Profile1.setText("Profil");
        Button_Profile1.setBorderPainted(false);
        jPanel1.add(Button_Profile1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 176, 39));

        Button_Dashboard.setText("Dashboard");
        Button_Dashboard.setBorderPainted(false);
        Button_Dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_DashboardActionPerformed(evt);
            }
        });
        jPanel1.add(Button_Dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 176, 39));

        Button_Logout1.setText("Logout");
        Button_Logout1.setBorderPainted(false);
        Button_Logout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Logout1ActionPerformed(evt);
            }
        });
        jPanel1.add(Button_Logout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 176, 39));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 57, -1, 560));

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        Label_Dosen.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Label_Dosen.setForeground(new java.awt.Color(255, 255, 255));
        Label_Dosen.setText("Dashboard Dosen");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_Dosen, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(785, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Label_Dosen)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 22)); // NOI18N
        jLabel1.setText("👋 Selamat Datang ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        jScrollPane1.setViewportView(jTable1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mata Kuliah", "Id_kelas", "Hari", "Jam", "Ruangan"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jScrollPane1.setViewportView(jScrollPane2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 600, 200));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel3.setText("Kelas Yang Di Ajar ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    private void Button_PresensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_PresensiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_PresensiActionPerformed

    private void Button_DashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_DashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_DashboardActionPerformed

    private void Button_Logout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Logout1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_Logout1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard_Dosen().setVisible(true));
    }
    
   

    // 1. SETTER NAMA (Untuk menampilkan "Selamat Datang, [Nama Dosen]")
    public void setNamaDosen(String nama) {
        jLabel1.setText("👋 Selamat Datang, " + nama);
    }

    // 2. GETTER TOMBOL (Agar bisa diklik lewat Controller)
    public javax.swing.JButton getButtonPresensi() { return Button_Presensi; }
    public javax.swing.JButton getButtonKelas() { return Button_KelasSaya; } // Kelas Saya
    public javax.swing.JButton getButtonNilai() { return Button_Nilai; }
    public javax.swing.JButton getButtonProfil() { return Button_Profile1; }
    public javax.swing.JButton getButtonLogout() { return Button_Logout1; }

    // 3. SETTER TABEL (Untuk mengisi daftar kelas)
    public void setTabelKelas(javax.swing.table.DefaultTableModel model) {
        jTable1.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Dashboard;
    private javax.swing.JButton Button_KelasSaya;
    private javax.swing.JButton Button_Logout1;
    private javax.swing.JButton Button_Nilai;
    private javax.swing.JButton Button_Presensi;
    private javax.swing.JButton Button_Profile1;
    private javax.swing.JLabel Label_Dosen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
