/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * @author Ahisar Pranowo
 */
public class Data_Dosen extends javax.swing.JFrame {
    
    private Controller.DataDosenController controller;

    public void setController(Controller.DataDosenController controller) {
        this.controller = controller;
    }
    /**
     * Creates new form Data_Dosen
     */
    public Data_Dosen() {
        initComponents();
        this.setSize(900, 700);  
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Label_Mahasiswa = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_DataDosen = new javax.swing.JTable();
        Button_Kembali = new javax.swing.JButton();
        Button_Hapus = new javax.swing.JButton();
        Button_Edit = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        Label_Mahasiswa.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Label_Mahasiswa.setForeground(new java.awt.Color(255, 255, 255));
        Label_Mahasiswa.setText("Data Dosen");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Label_Mahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(695, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Label_Mahasiswa)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        jScrollPane2.setViewportView(Table_DataDosen);

        Table_DataDosen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NIP", "Nama Dosen", "Email", "Prodi"
            }
        ));
        jScrollPane1.setViewportView(Table_DataDosen);

        jScrollPane2.setViewportView(jScrollPane1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 800, 360));

        Button_Kembali.setText("Kembali");
        Button_Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_KembaliActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 134, -1));

        Button_Hapus.setText("Hapus");
        Button_Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_HapusActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, -1, -1));

        Button_Edit.setText("Edit");
        Button_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_EditActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 450, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void Button_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_HapusActionPerformed
        // TODO add your handling code here:
        if (controller != null) controller.klikHapus();
    }//GEN-LAST:event_Button_HapusActionPerformed

    private void Button_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_EditActionPerformed
        // TODO add your handling code here:
        if (controller != null) controller.klikEdit();
    }//GEN-LAST:event_Button_EditActionPerformed

    private void Button_KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_KembaliActionPerformed
        // TODO add your handling code here:
        if (controller != null) controller.klikKembali();
    }//GEN-LAST:event_Button_KembaliActionPerformed
    
    
    // ... (Getter dan Setter lain TETAP SAMA) ...
    public javax.swing.JTable getTable() { return Table_DataDosen; }
    public javax.swing.JButton getButtonKembali() { return Button_Kembali; }
    public javax.swing.JButton getButtonHapus() { return Button_Hapus; }
    public javax.swing.JButton getButtonEdit() { return Button_Edit; } 

    public void setTabelDosen(javax.swing.table.DefaultTableModel model) {
        Table_DataDosen.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Edit;
    private javax.swing.JButton Button_Hapus;
    private javax.swing.JButton Button_Kembali;
    private javax.swing.JLabel Label_Mahasiswa;
    private javax.swing.JTable Table_DataDosen;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
