/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ahisar Pranowo
 */
public class Jadwal extends javax.swing.JPanel {

    /**
     * Creates new form Jadwal
     */
    public Jadwal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Label_Jadwal = new javax.swing.JLabel();
        Label_Filter = new javax.swing.JLabel();
        ComboBox_Hari = new javax.swing.JComboBox<>();
        Label_Hari = new javax.swing.JLabel();
        Button_Kembali = new javax.swing.JButton();
        ScrollPane_Jadwal = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Jadwal = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        Label_Jadwal.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        Label_Jadwal.setForeground(new java.awt.Color(255, 255, 255));
        Label_Jadwal.setText("📅 JADWAL KULIAH ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Label_Jadwal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Label_Jadwal)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        Label_Filter.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        Label_Filter.setText("FILTER :");

        ComboBox_Hari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua ", "Senin", "Selasa", "Rabu", "Kamis ", "Jumat", "Sabtu" }));
        ComboBox_Hari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_HariActionPerformed(evt);
            }
        });

        Label_Hari.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        Label_Hari.setText("Hari");

        Button_Kembali.setText("Kembali");
        Button_Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_KembaliActionPerformed(evt);
            }
        });

        ScrollPane_Jadwal.setViewportView(Table_Jadwal);

        Table_Jadwal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Hari", "Mata Kuliah", "Jam", "Ruang", "Dosen", "Status"
            }
        ));
        jScrollPane1.setViewportView(Table_Jadwal);

        ScrollPane_Jadwal.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_Filter)
                .addGap(17, 17, 17)
                .addComponent(Label_Hari, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(ComboBox_Hari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 806, Short.MAX_VALUE)
                .addComponent(Button_Kembali)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ScrollPane_Jadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Filter)
                    .addComponent(ComboBox_Hari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Hari, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(ScrollPane_Jadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(Button_Kembali)
                .addGap(0, 35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBox_HariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_HariActionPerformed
        // TODO add your handling code here:
        if (controller != null) {
            controller.filterHari();
        }
    }//GEN-LAST:event_ComboBox_HariActionPerformed

    private void Button_KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_KembaliActionPerformed
        // TODO add your handling code here:
        if (controller != null) {
            controller.kembali();
        }
    }//GEN-LAST:event_Button_KembaliActionPerformed

    // 1. Untuk Mengakses Tabel dari Controller
   public void setJadwalTable(DefaultTableModel model) {
    Table_Jadwal.setModel(model);
}
    // 2. Untuk Mengakses Tombol Kembali
    public javax.swing.JButton getBtnKembali() {
        // Ganti 'jButtonKembali' dengan nama variabel tombol kembali Anda
        return Button_Kembali; 
    }
    
    private Controller.JadwalController controller;

    public void setController(Controller.JadwalController controller) {
        this.controller = controller;
    }
    
    // Getter untuk ComboBox (Agar Controller bisa baca isinya)
    public javax.swing.JComboBox<String> getComboBoxHari() {
        return ComboBox_Hari; // Sesuaikan dengan nama variabel ComboBox Anda
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Kembali;
    private javax.swing.JComboBox<String> ComboBox_Hari;
    private javax.swing.JLabel Label_Filter;
    private javax.swing.JLabel Label_Hari;
    private javax.swing.JLabel Label_Jadwal;
    private javax.swing.JScrollPane ScrollPane_Jadwal;
    private javax.swing.JTable Table_Jadwal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
