/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * @author Ahisar Pranowo
 */
public class Jadwal extends javax.swing.JPanel {

    /**
     * Creates new form Jadwal
     */
    public Jadwal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Label_Jadwal = new javax.swing.JLabel();
        Label_Filter = new javax.swing.JLabel();
        ComboBox_Hari = new javax.swing.JComboBox<>();
        Label_Hari = new javax.swing.JLabel();
        Label_Semester = new javax.swing.JLabel();
        ComboBox_Semester = new javax.swing.JComboBox<>();
        Button_Refresh = new javax.swing.JButton();
        Label_Info = new javax.swing.JLabel();
        Label_Back = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Jadwal = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        Label_Jadwal.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        Label_Jadwal.setForeground(new java.awt.Color(255, 255, 255));
        Label_Jadwal.setText("📅 JADWAL KULIAH ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Label_Jadwal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Label_Jadwal)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        Label_Filter.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        Label_Filter.setText("FILTER :");

        ComboBox_Hari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua ", "Senin", "Selasa", "Rabu", "Kamis ", "Jumat", "Sabtu" }));
        ComboBox_Hari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_HariActionPerformed(evt);
            }
        });

        Label_Hari.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        Label_Hari.setText("Hari");

        Label_Semester.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        Label_Semester.setText("Semester");

        ComboBox_Semester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        ComboBox_Semester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_SemesterActionPerformed(evt);
            }
        });

        Button_Refresh.setText("Refresh");

        Label_Info.setText("|   Informasi status :    Tidak bentrok   Warning    Bentrok |");

        Label_Back.setText("Kembali");
        Label_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Label_BackActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(Table_Jadwal);

        Table_Jadwal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Hari", "Mata Kuliah", "Jam", "Ruang", "Dosen", "Status"
            }
        ));
        jScrollPane1.setViewportView(Table_Jadwal);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_Filter)
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Label_Semester, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_Hari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(24, 24, 24)
                        .addComponent(ComboBox_Hari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Button_Refresh)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(ComboBox_Semester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 806, Short.MAX_VALUE)
                .addComponent(Label_Back)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Info)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Filter)
                    .addComponent(ComboBox_Hari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Hari, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Refresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Semester, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBox_Semester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(Label_Info, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(Label_Back)
                .addGap(0, 34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBox_HariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_HariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox_HariActionPerformed

    private void ComboBox_SemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_SemesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox_SemesterActionPerformed

    private void Label_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Label_BackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Label_BackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Refresh;
    private javax.swing.JComboBox<String> ComboBox_Hari;
    private javax.swing.JComboBox<String> ComboBox_Semester;
    private javax.swing.JButton Label_Back;
    private javax.swing.JLabel Label_Filter;
    private javax.swing.JLabel Label_Hari;
    private javax.swing.JLabel Label_Info;
    private javax.swing.JLabel Label_Jadwal;
    private javax.swing.JLabel Label_Semester;
    private javax.swing.JTable Table_Jadwal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
