/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.KSTController;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ahisar Pranowo
 */
public class KST extends javax.swing.JPanel {

    /**
     * Creates new form KST
     */
    public KST() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        TextField_NIM = new javax.swing.JTextField();
        TextField_Nama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ScrollPane_KST = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_KST = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        Label_Mahasiswa = new javax.swing.JLabel();
        Button_HapusMK = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Button_Kembali = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        jLabel2.setText("NIM :");

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setText("Matakuliah yang sudah diambil");

        Table_KST.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode MK ", "Matakuliah", "SKS", "Hari", "Waktu"
            }
        ));
        jScrollPane1.setViewportView(Table_KST);

        ScrollPane_KST.setViewportView(jScrollPane1);

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        Label_Mahasiswa.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Label_Mahasiswa.setForeground(new java.awt.Color(255, 255, 255));
        Label_Mahasiswa.setText("Kartu Studi Tetap");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Label_Mahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(764, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Label_Mahasiswa)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        Button_HapusMK.setText("Hapus MK");
        Button_HapusMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_HapusMKActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        jLabel1.setText("Nama :");

        Button_Kembali.setText("Kembali");
        Button_Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_KembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Button_HapusMK, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ScrollPane_KST, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(36, 36, 36)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TextField_NIM, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                .addComponent(TextField_Nama)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(Button_Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TextField_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TextField_NIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ScrollPane_KST, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_HapusMK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Button_Kembali)
                .addGap(0, 43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Button_HapusMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_HapusMKActionPerformed
        // TODO add your handling code here:
        int selectedRow = Table_KST.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih matakuliah yang ingin dihapus terlebih dahulu!");
            return;
        }
        
        // 2. Ambil Kode MK dari baris yang dipilih (Kolom ke-0)
        String kodeMk = Table_KST.getValueAt(selectedRow, 0).toString();
        
        // 3. Panggil Controller untuk menghapus
        if (controller != null) {
            controller.hapusMatakuliah(kodeMk);
        } else {
            System.out.println("Controller belum terhubung!");
        }
    }//GEN-LAST:event_Button_HapusMKActionPerformed

    private void Button_KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_KembaliActionPerformed
        // TODO add your handling code here:
        if (controller != null) {
            controller.kembali();
        } else {
            System.out.println("Controller belum terhubung!");
        }
    }//GEN-LAST:event_Button_KembaliActionPerformed

      public void setNamaMahasiswa(String nama) {
        // Ganti 'TextField_Nama' sesuai nama variabel di desain Anda
        TextField_Nama.setText(nama);
    }

    public void setNimMahasiswa(String nim) {
        // Ganti 'TextField_NIM' sesuai nama variabel di desain Anda
        TextField_NIM.setText(nim);
    }

    // 2. Setter untuk Tabel
    public void setTableKST(DefaultTableModel model) {
        // Ganti 'Table_KST' sesuai nama variabel tabel Anda
        Table_KST.setModel(model);
    }
    
    // 3. Getter Tombol
    public javax.swing.JButton getBtnKembali() {
        // Ganti 'Button_Kembali' sesuai nama tombol Anda
        return Button_Kembali;
    }

    public javax.swing.JButton getBtnHapus() {
        // Ganti 'Button_Hapus' sesuai nama tombol Anda
        return Button_HapusMK; 
    }
    
    // --- TAMBAHKAN VARIABEL INI ---
    private KSTController controller;

    // --- TAMBAHKAN METHOD SETTER INI ---
   public void setController(KSTController controller) {
    this.controller = controller;
    }

    
    // Pastikan Anda juga punya getter tabel ini (untuk fitur hapus nanti)
    public javax.swing.JTable getTableKST() {
        return Table_KST;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_HapusMK;
    private javax.swing.JButton Button_Kembali;
    private javax.swing.JLabel Label_Mahasiswa;
    private javax.swing.JScrollPane ScrollPane_KST;
    private javax.swing.JTable Table_KST;
    private javax.swing.JTextField TextField_NIM;
    private javax.swing.JTextField TextField_Nama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
