/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Ahisar Pranowo
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Label_Login = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        Label_Password = new javax.swing.JLabel();
        Label_Username = new javax.swing.JLabel();
        Textfield_Username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 204, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOGIN");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(681, 438, 117, 38));

        Label_Login.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Label_Login.setForeground(new java.awt.Color(255, 255, 255));
        Label_Login.setText("LOGIN SIASAT");
        jPanel1.add(Label_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        PasswordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });
        jPanel1.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 200, 210, 30));

        Label_Password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label_Password.setForeground(new java.awt.Color(255, 255, 255));
        Label_Password.setText("Password");
        jPanel1.add(Label_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 204, -1, -1));

        Label_Username.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label_Username.setForeground(new java.awt.Color(255, 255, 255));
        Label_Username.setText("Username/nim/nip");
        jPanel1.add(Label_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 124, -1, -1));

        Textfield_Username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Textfield_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Textfield_UsernameActionPerformed(evt);
            }
        });
        jPanel1.add(Textfield_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 120, 210, 30));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("*Notes* : gunakan username untuk login sebagai dosen, gunakan nim untuk login sebgai mahasiswa, dan nip untuk dosen");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Textfield_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Textfield_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Textfield_UsernameActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }
    
    public String getUsernameInput() {
            // Mengambil teks dari Textfield_Username
            return Textfield_Username.getText();
        }

        public String getPasswordInput() {
            // Mengambil password dari PasswordField
            return new String(PasswordField.getPassword());
        }

        public javax.swing.JButton getBtnLogin() {
            // Memberikan akses tombol login ke Controller
            return jButton1;
        }

        // Opsional: Agar field password juga bisa didengar Action-nya (misal tekan Enter)
        public javax.swing.JPasswordField getPasswordField() {
            return PasswordField;
        }

        // Method untuk menampilkan pesan error/sukses dari Controller
        public void showMessage(String message) {
            javax.swing.JOptionPane.showMessageDialog(this, message);
        }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_Login;
    private javax.swing.JLabel Label_Password;
    private javax.swing.JLabel Label_Username;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JTextField Textfield_Username;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
