/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * @author Ahisar Pranowo
 */
public class ToDo_List extends javax.swing.JPanel {
    
    private Controller.TodoListController controller;

    public void setController(Controller.TodoListController controller) {
        this.controller = controller;
    }

    /**
     * Creates new form ToDo_List
     */
    public ToDo_List() {
        initComponents();
        
        ((javax.swing.JTextField) DateChooser_Deadline.getDateEditor().getUiComponent()).setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_Selesai = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_Todo = new javax.swing.JTable();
        RadioButton_Pending = new javax.swing.JRadioButton();
        RadioButton_Proses = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        RadioButton_Selesai = new javax.swing.JRadioButton();
        ComboBox_Prioritas = new javax.swing.JComboBox<>();
        Button_Kembali = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea_Deskripsi = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Button_Tambah = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Button_Update = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Button_Hapus = new javax.swing.JButton();
        TextField_Judul = new javax.swing.JTextField();
        DateChooser_Deadline = new com.toedter.calendar.JDateChooser();

        Button_Selesai.setText("Tandai Selesai");

        Table_Todo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Judul", "Deadline", "Prioritas", "Status"
            }
        ));
        jScrollPane2.setViewportView(Table_Todo);

        jScrollPane3.setViewportView(jScrollPane2);

        RadioButton_Pending.setText("Pending");
        RadioButton_Pending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton_PendingActionPerformed(evt);
            }
        });

        RadioButton_Proses.setText("Proses");

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("To-Do List");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        RadioButton_Selesai.setText("Selesai");

        ComboBox_Prioritas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tinggi", "Sedang", "Rendah" }));

        Button_Kembali.setText("Kembali");
        Button_Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_KembaliActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        jLabel2.setText("Judul :");

        TextArea_Deskripsi.setColumns(20);
        TextArea_Deskripsi.setRows(5);
        jScrollPane1.setViewportView(TextArea_Deskripsi);

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        jLabel3.setText("Deskripsi :");

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        jLabel4.setText("Prioritas :");

        Button_Tambah.setText("Tambah");
        Button_Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_TambahActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        jLabel5.setText("Deadline :");

        Button_Update.setText("Update");
        Button_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_UpdateActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        jLabel6.setText("Status :");

        Button_Hapus.setText("Hapus");
        Button_Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_HapusActionPerformed(evt);
            }
        });

        TextField_Judul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_JudulActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(22, 22, 22))
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ComboBox_Prioritas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(TextField_Judul, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(21, 21, 21)))
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(RadioButton_Pending)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RadioButton_Proses)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RadioButton_Selesai))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DateChooser_Deadline, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Button_Tambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Button_Update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Button_Hapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Button_Selesai))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Button_Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RadioButton_Pending)
                    .addComponent(RadioButton_Selesai)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(TextField_Judul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(RadioButton_Proses)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(DateChooser_Deadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ComboBox_Prioritas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Tambah)
                    .addComponent(Button_Update)
                    .addComponent(Button_Hapus)
                    .addComponent(Button_Selesai))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Button_Kembali)
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RadioButton_PendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton_PendingActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_RadioButton_PendingActionPerformed

    private void Button_KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_KembaliActionPerformed
        // TODO add your handling code here:
        if(controller!=null) controller.kembali();
    }//GEN-LAST:event_Button_KembaliActionPerformed

    private void Button_TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_TambahActionPerformed
        // TODO add your handling code here:
        if(controller!=null) controller.tambah();
    }//GEN-LAST:event_Button_TambahActionPerformed

    private void Button_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_UpdateActionPerformed
        // TODO add your handling code here:
        if (controller != null) {
            controller.update();
        }
    }//GEN-LAST:event_Button_UpdateActionPerformed

    private void Button_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_HapusActionPerformed
        // TODO add your handling code here:
        if(controller!=null) controller.hapus();
    }//GEN-LAST:event_Button_HapusActionPerformed

    private void TextField_JudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_JudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_JudulActionPerformed

    
    // --- 1. GETTER INPUTAN ---
    public String getInputJudul() { return TextField_Judul.getText(); }
    public java.util.Date getInputDeadline() { 
        return DateChooser_Deadline.getDate(); 
    }
    public String getInputDeskripsi() { return TextArea_Deskripsi.getText(); }
    
    public String getInputPrioritas() { 
        return ComboBox_Prioritas.getSelectedItem().toString(); 
    }
    
    public String getInputStatus() {
        if (RadioButton_Pending.isSelected()) return "pending";
        if (RadioButton_Proses.isSelected()) return "proses";
        if (RadioButton_Selesai.isSelected()) return "selesai";
        return "pending"; 
    }
    
    // --- 2. AKSES TABEL ---
    public javax.swing.JTable getTableTodo() { return Table_Todo; }
    
    public void setTabelTodo(javax.swing.table.DefaultTableModel model) {
        Table_Todo.setModel(model);
    }
    
    // --- 3. SETTER (Untuk mengisi form saat tabel diklik) ---
    public void setJudul(String judul) { TextField_Judul.setText(judul); }
    public void setDeadline(java.util.Date date) { 
        DateChooser_Deadline.setDate(date); 
    }  
    public void setDeskripsi(String ket) { TextArea_Deskripsi.setText(ket); }
    
    public void setPrioritas(String prio) { 
        ComboBox_Prioritas.setSelectedItem(prio); 
    }
    
    public void setStatus(String status) {
        if (status.equalsIgnoreCase("pending")) RadioButton_Pending.setSelected(true);
        else if (status.equalsIgnoreCase("proses")) RadioButton_Proses.setSelected(true);
        else if (status.equalsIgnoreCase("selesai")) RadioButton_Selesai.setSelected(true);
    }
    
    public void resetForm() {
        TextField_Judul.setText("");
        DateChooser_Deadline.setDate(null);
        TextArea_Deskripsi.setText("");
        ComboBox_Prioritas.setSelectedIndex(0);
        RadioButton_Pending.setSelected(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Hapus;
    private javax.swing.JButton Button_Kembali;
    private javax.swing.JButton Button_Selesai;
    private javax.swing.JButton Button_Tambah;
    private javax.swing.JButton Button_Update;
    private javax.swing.JComboBox<String> ComboBox_Prioritas;
    private com.toedter.calendar.JDateChooser DateChooser_Deadline;
    private javax.swing.JRadioButton RadioButton_Pending;
    private javax.swing.JRadioButton RadioButton_Proses;
    private javax.swing.JRadioButton RadioButton_Selesai;
    private javax.swing.JTable Table_Todo;
    private javax.swing.JTextArea TextArea_Deskripsi;
    private javax.swing.JTextField TextField_Judul;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
